SET IDENTITY_INSERT [dbo].[Blogs] ON
INSERT INTO [dbo].[Blogs] ([BlogId], [Title], [Subject], [Text], [Quote], [QuoteFrom], [SubTitle], [SubText], [Bullet], [ImgUrl], [Date], [ThemeId], [Type]) VALUES (0, N'Products are sourced from where they grow', N'S o u r c e', N'Our expert of the innovation team tells you about it. Donec ullamcorper nulla non metus auctor fringilla. Sed Posuere Consectetur est at lobortis. Maecenas faucibus mollis interdum. Sed posuere consectetur est at lobortis.', N'We travel around the world to find inspiration for our products', N'J. ter Heijde (Innovation team Verstegen)', N'Integer posuere erat a ante venenatis daplibus', N'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters nam en ze door elkaar husselde om een font-catalogus te maken. Het heeft niet alleen vijf eeuwen overleefd maar is ook, vrijwel onveranderd, overgenomen in elektronische letterzetting.', N'', N'images/Stories/field-worker.jpg', N'2019-01-09 18:32:16', 0, N'')
INSERT INTO [dbo].[Blogs] ([BlogId], [Title], [Subject], [Text], [Quote], [QuoteFrom], [SubTitle], [SubText], [Bullet], [ImgUrl], [Date], [ThemeId], [Type]) VALUES (1, N'We process everything in our own factory', N' ', N'Our expert of the innovation team tells you about it. Donec ullamcorper nulla non metus auctor fringilla. Sed Posuere Consectetur est at lobortis. Maecenas faucibus mollis interdum. Sed posuere consectetur est at lobortis.', N'We travel around the world to find inspiration for our products', N'J. ter Heijde (Innovation team Verstegen)', N'Integer posuere erat a ante venenatis daplibus', N'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters nam en ze door elkaar husselde om een font-catalogus te maken. Het heeft niet alleen vijf eeuwen overleefd maar is ook, vrijwel onveranderd, overgenomen in elektronische letterzetting.', N'', N'images/Stories/lab-worker.jpg', N'2019-01-09 18:32:16', 0, N'')
INSERT INTO [dbo].[Blogs] ([BlogId], [Title], [Subject], [Text], [Quote], [QuoteFrom], [SubTitle], [SubText], [Bullet], [ImgUrl], [Date], [ThemeId], [Type]) VALUES (2, N'Standard and custom made products', N'C u s t o m  v s  s t a n d a r d', N'Our expert of the innovation team tells you about it. Donec ullamcorper nulla non metus auctor fringilla. Sed Posuere Consectetur est at lobortis. Maecenas faucibus mollis interdum. Sed posuere consectetur est at lobortis.', N'We travel around the world to find inspiration for our products', N'J. ter Heijde (Innovation team Verstegen)', N'Integer posuere erat a ante venenatis daplibus', N'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters nam en ze door elkaar husselde om een font-catalogus te maken. Het heeft niet alleen vijf eeuwen overleefd maar is ook, vrijwel onveranderd, overgenomen in elektronische letterzetting.', N'', N'images/Stories/chef-worker.jpg', N'2019-01-09 18:32:16', 0, N'')
INSERT INTO [dbo].[Blogs] ([BlogId], [Title], [Subject], [Text], [Quote], [QuoteFrom], [SubTitle], [SubText], [Bullet], [ImgUrl], [Date], [ThemeId], [Type]) VALUES (3, N'The product is important, but partnership is everything', N' ', N'Our expert of the innovation team tells you about it. Donec ullamcorper nulla non metus auctor fringilla. Sed Posuere Consectetur est at lobortis. Maecenas faucibus mollis interdum. Sed posuere consectetur est at lobortis.', N'We travel around the world to find inspiration for our products', N'J. ter Heijde (Innovation team Verstegen)', N'Integer posuere erat a ante venenatis daplibus', N'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters nam en ze door elkaar husselde om een font-catalogus te maken. Het heeft niet alleen vijf eeuwen overleefd maar is ook, vrijwel onveranderd, overgenomen in elektronische letterzetting.', N'', N'images/Stories/hand-seasoning.jpg', N'2019-01-09 18:32:16', 0, N'')
SET IDENTITY_INSERT [dbo].[Blogs] OFF

SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (0, N'Aardappel, Groente, Fruit', N'agf')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (1, N'Kant-enklaar, Salades', N'k&ks')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (2, N'Vlees, Kip, Vis, Vega', N'vkvv')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (3, N'Kaas, Vleeswaren, Delicatessen', N'kvd')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (4, N'Zuivel, Eieren', N'ze')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (5, N'Bakkerij', N'bk')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (6, N'Ontbijtgranen, Broodbeleg, Tussendoor', N'obt')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (7, N'Frisdrank, Sappen, Koffie, Thee', N'fskt')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (8, N'Bier, Sterke drank, Apperatieven', N'bsa')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (9, N'Pasta, Rijst, Internationale keuken', N'pri')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (10, N'Soepen, Conserven, Sauzen, Smaakmakers', N'scss')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (11, N'Snoep, Koek, Chips', N'skc')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (12, N'Diepvries', N'dpv')
INSERT INTO [dbo].[Categories] ([CategoryId], [CategoryName], [CategoryValue]) VALUES (13, N'Bewuste voeding', N'bwv')
SET IDENTITY_INSERT [dbo].[Categories] OFF

SET IDENTITY_INSERT [dbo].[Contacts] ON
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (0, N'Jan den Heijer', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)622571514', N'hhensen@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (1, N'Gerrit de Jong', N'Web Developer', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (2, N'Tom van Velden', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (3, N'Jonathan de Greef', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (4, N'Joost de Niet', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (5, N'Thijs van Rheenen', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (6, N'Mustafa', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (7, N'Erik Engelgeer', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
INSERT INTO [dbo].[Contacts] ([ContactId], [Name], [Function], [Country], [Province], [Tel], [Email], [ImgUrl]) VALUES (8, N'Adeel Shani', N'Director of Sales & Marketing Food Industry', N'The Netherland', N'Zuid-Holland', N'+31(0)532534344', N'gdjong@verstegen.nl', N'/images/icons/persoon_img.svg')
SET IDENTITY_INSERT [dbo].[Contacts] OFF

SET IDENTITY_INSERT [dbo].[Ingredients] ON
INSERT INTO [dbo].[Ingredients] ([IngredientId], [Name], [ArticleNumber], [Gram], [Percentage], [RecipeId]) VALUES (0, N'Rundersnippers 85/15', NULL, 860, 68.8, 1)
INSERT INTO [dbo].[Ingredients] ([IngredientId], [Name], [ArticleNumber], [Gram], [Percentage], [RecipeId]) VALUES (1, N'Water', NULL, 60, 20, 1)
INSERT INTO [dbo].[Ingredients] ([IngredientId], [Name], [ArticleNumber], [Gram], [Percentage], [RecipeId]) VALUES (2, N'Snijbare Champignonsaus', NULL, 250, 20, 1)
INSERT INTO [dbo].[Ingredients] ([IngredientId], [Name], [ArticleNumber], [Gram], [Percentage], [RecipeId]) VALUES (3, N'World Spice Blend Mediterranean', NULL, 40, 3.2, 1)
INSERT INTO [dbo].[Ingredients] ([IngredientId], [Name], [ArticleNumber], [Gram], [Percentage], [RecipeId]) VALUES (4, N'Binding Vero Pure', NULL, 40, 3.2, 1)
SET IDENTITY_INSERT [dbo].[Ingredients] OFF

SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductId], [Title], [Type], [CategoryId], [Description], [Contents], [ProductDetails]) VALUES (0, N'Kruidenmix', N'Vlees', 2, N'Kruidenmix oor gehakt (natrium)', N'40g', N'Koop
Zonder zout eten hoeft helemaal niet smaakloos te zijn. Als je maar de juiste ingrediënten gebruikt. En dat is precies wat wij hebben gedaan: door de juiste smaakvolle kruiden en specerijen te gebruiken breng je ook zonder zout je gerecht heerlijk op smaak.')
INSERT INTO [dbo].[Products] ([ProductId], [Title], [Type], [CategoryId], [Description], [Contents], [ProductDetails]) VALUES (1, N'Mix voor aardappel', N'Aardappel', 0, N'Mix voor aardappel', N'80g', N'Koop
Wat velen niet weten is dat wij naast de bekende mixen voor gehakt en kip ook verschillende mixen hebben voor je maaltijd. Met deze mixen kun je met één zakje je gehele maaltijd op smaak brengen. Heerlijke winterse Hachee, Goulash of Chili con Carne of verschillende stamppotten, met Verstegen chef je het allemaal zelf.')
SET IDENTITY_INSERT [dbo].[Products] OFF

SET IDENTITY_INSERT [dbo].[Recipes] ON
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (0, N'Sausage', N'Grilled pork sausages', N'Meat', N'For 5 sausages', N'images/recipes/preview/sausages.jpg', N'Grind the meat_make sausage_grill the sausage and you''re done', N'BBQ Sauce_Garlic Sauce', 0)
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (1, N'Burger', N'Burgers with fries and coleslaw', N'Meat', N'For 5 burgers', N'images/recipes/preview/burger.jpg', N'Grill the burger on a high pit_(optional) grill the bread aswell_Slice some tomatoes_When the meat is done you can start building your burger!', N'BBQ Sauce_Bacon', 0)
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (2, N'Salmon', N'Salmon with fresh vegetables', N'Fish', N'For 5 plates', N'images/recipes/preview/salmon.jpg', N'Slice the salmon_Bake the vegetables with some oil_grill the salmon_serve together in a bowl', N'Dill_Rucola', 0)
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (3, N'Oatmeal', N'Oatmeal with fresh fruits', N'Breakfast', N'For 2 bowls', N'images/recipes/preview/oatmeal-fruits.jpg', N'Warm up some milk and put it in a bowl_Add the oatmeal_Add any fruits you fancy_enjoy your meal!', N'Fresh mint_Extra fruits', 0)
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (4, N'Pancakes', N'Pancakes with fruits', N'Breakfast', N'For 10 pancakes', N'images/recipes/preview/pancakes.jpg', N'Add the flower, milk and eggs in a bowl_Mix the contents for 2 minutes_Warm up a pan and make some pancakes', N'Sugar_Bacon', 0)
INSERT INTO [dbo].[Recipes] ([RecipeId], [Title], [SubTitle], [Type], [AmountOfPeople], [ImgUrl], [Procedure], [Decoration], [ThemeId]) VALUES (6, N'Pasta Pesto', N'Pasta with fresh pesto and spinach', N'Pasta', N'For 3 bowls', N'images/recipes/preview/sausages.jpg', N'Boil the pasta for 10 minutes_Cook the chicken in the meantime_When the pasta is done, combine with the chicken_Final touch, add the pesto ', N'Pine nuts_Rucola', 0)
SET IDENTITY_INSERT [dbo].[Recipes] OFF

SET IDENTITY_INSERT [dbo].[Themes] ON
INSERT INTO [dbo].[Themes] ([ThemeId], [Name], [ImgUrl], [IconUrl]) VALUES (0, N'Easter', N'https://images2.alphacoders.com/661/661074.jpg', N'easter-egg-icon.svg')
INSERT INTO [dbo].[Themes] ([ThemeId], [Name], [ImgUrl], [IconUrl]) VALUES (1, N'Thanksgiving', N'https://www.kiss1023.ca/wp-content/blogs.dir/10/files/Holiday_Thanksgiving_Turkey-Dinner-Picture-2012-HD-Wallpaper-1.jpg', N'chicken-icon.svg')
SET IDENTITY_INSERT [dbo].[Themes] OFF
